config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  root to: 'blogs#index'
  resources :blogs, except: [:show] do
    member do
      post 'like'
      post 'bookmark' => 'users#bookmark'
    end
  end
  resources :comments
  resources :tags
  get 'tags-name-list' => 'tags#name_list'
  get '/trending' => 'home#trending', as: 'trending'
  get '/search' => 'home#search', as: 'search'
  resources :categories
  post '/follow_update' => 'followers#follow_update'
  devise_for :users, :controllers => {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "sessions",
    registrations: "registrations"
  }
  get '/bookmarked-articles' => 'users#bookmarked', as: 'bookmarked_articles'
  resources :users, only: [:show, :edit, :update] do
    member do
      put 'update_username'
      get 'comments'
      get 'following/suggestions' => 'users#following_suggestions', as: 'follow_suggestions'
      get 'following/categories' => 'users#following_categories', as: 'follow_categories'
      get 'following/people' => 'users#following_people', as: 'follow_people'
      get 'following/tags' => 'users#following_tags', as: 'follow_tags'
    end
  end
  get '/:category_id/:id' => 'blogs#show', as: 'blog_show'
  post '/image_upload' => 'attachments#image_upload'
end

app/models/blog.rb
class Blog < ApplicationRecord

  include Searchable

  extend FriendlyId

  friendly_id :title, use: :slugged

  after_commit on: [:create, :update] do
    es_reindex
  end

  after_commit on: [:destroy] do
    es_delete_index
  end

  belongs_to :user
  belongs_to :category
  has_many :comments
  has_many :likes
  has_many :taggings
  has_many :tags, through: :taggings

  after_save :process_description
  after_create :update_blogs_count
  after_commit :blog_count_update

  enum status: {draft: 0, live: 1}

  default_scope {where.not(status: 0)}

  def self.trending_blogs
    trending_days = 140
    where('created_at::DATE >= ?', Date.today - trending_days.days).order(likes_count: :desc)
  end

  def as_indexed_json(options = {})
    self.as_json(
      only: [:title, :description, :slug, :short_description, :updated_at, :likes_count, :comments_count],
      methods: [ :user_name, :user_username, :category_name, :category_slug ]
    )
  end

  def user_name
    user.name || ''
  end

  def user_username
    user.username
  end

  def category_slug
    category.slug
  end

  def category_name
    category.name
  end

  private

  def blog_count_update
    user.update_attribute(:blogs_count, user.blogs.count)
  end

  def process_description
    short_desc = ActionView::Base.full_sanitizer.sanitize(description).first(200) + ' .....'
    update_column(:short_description, short_desc)
  end

  def update_blogs_count
    category.update_column(:blogs_count, category.blogs.count)
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  # before_action :set_category, only: [:show]
  before_action :set_blog, only: [:like, :bookmark]
  before_action :set_unscoped_blog, only: [:edit, :update]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :like]
  before_action :authorize_user, only: [:edit, :update]

  def index
    @blogs = Blog.order(id: :desc).page(params[:page]).per(12)
    @home_tags = Tagging.home_tags(4)
    @trending_categories = Category.select('id,name,blogs_count,slug').order(blogs_count: :desc).limit(4)
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = current_user.blogs.new(blog_params.except(:tag_list,:draft))
    @blog.status = blog_params[:draft] ? 0 : 1
    if @blog.save
      blog_params[:tag_list].gsub(' ', '').split(',').each do |tag_name|
        tag = Tag.find_or_create_by(name: tag_name)
        tagging = tag.taggings.new(blog_id: @blog.id, user_id: current_user.id)
        tagging.save
      end
      redirect_to @blog.draft? ? user_path(current_user.username) : @blog
    else
      render 'new'
    end
  end

  def show
    category = Category.find_by(slug: params[:category_id])
    if category
      @blog = category.blogs.find_by(slug: params[:id])
      if @blog.blank?
        render :file => 'public/404', :status => :not_found, :layout => true
      end
    else
      set_blog
      redirect_to blog_show_path(id: @blog, category_id: @blog.category) if @blog
    end
    @comments = @blog.comments.order(id: :desc) if @blog
  end

  def edit
  end

  def update
    if @blog.update_attributes(blog_params.except(:tag_list))
      blog_params[:tag_list].gsub(' ', '').split(',').each do |tag_name|
        tag = Tag.find_or_create_by(name: tag_name)
        tagging = tag.taggings.find_or_create_by(blog_id: @blog.id, user_id: current_user.id)
      end
      redirect_to @blog.draft? ? user_path(current_user.username) : @blog
    else
      render 'edit'
    end
  end

  def like
    like = @blog.likes.find_or_initialize_by(user_id: current_user.id)
    like.hits += 1
    unless like.save
      @errors = like.errors.full_messages
    end
    respond_to do |format|
      format.js
    end
  end

  private

  def set_blog
    unless @blog = Blog.find_by(slug: params[:id])
      render :file => 'public/404', :status => :not_found, :layout => true
    end
  end

  def set_unscoped_blog
    unless @blog = Blog.unscoped.find_by(slug: params[:id])
      render :file => 'public/404', :status => :not_found, :layout => true
    end
  end

  def blog_params
    params.require(:blog).permit(:id, :title, :description, :category_id, :tag_list, :draft)
  end

  def authorize_user
    unless @blog.user == current_user
      render :file => 'public/404', :status => :not_found, :layout => true
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def get_categories
    @categories_list ||= Category.order(name: :asc).collect{ |category| [category.name, category.id]}
  end

  def get_countries
    Country.order(name: :asc).collect{ |country| [country.name, country.id]}
  end
end

app/views/blogs/_blogs.html.erb
<% if @blogs.present? %>
  <% @blogs.each_with_index do |blog, index| %>
    <% if ((index + 1) % 4 == 0) %>
      <div class="content-wrap c-wrap">
        <div>google ad</div>
      </div>
    <% end %>
    <!-- .content-wrap -->
    <div class="content-wrap c-wrap">
      <div class="share-blog">
        <div class="m-share">
          <a class="theme-share sharebtn mshare-btn fa fa-share" aria-hidden="true" href="#"></a>
        </div>
        <div class="d-share">
          <% blog_url = blog_show_url(id: blog, category_id: blog.category) %>
          <a class="facebook-share sharebtn fa fa-facebook" aria-hidden="true" href="http://www.facebook.com/share.php?quote=<%= blog.title %>&u=<%= blog_url %>" target="blank"></a>
          <a class="twitter-share sharebtn fa fa-twitter" aria-hidden="true" href="https://twitter.com/intent/tweet?text=<%= blog.title %> <%= blog_url %>" target="blank"></a>
          <a class="whatsapp-share sharebtn fa fa-whatsapp" aria-hidden="true" href="https://api.whatsapp.com/send?text= <%= blog.title %> <%= blog_url %>." target="blank"></a>
          <a class="telegram-share sharebtn fab fa-telegram-plane" aria-hidden="true" href="https://t.me/share/url?url=<%= blog_url %>" target="blank"></a>
        </div>
      </div>
      <div class="blog-info">
        <div class="user-img">
          <% if blog.user.avatar.present? %>
            <img src="<%= blog.user.avatar %>" alt="user" class="rounded-circle">
          <% else %>
            <img class="card-img-top" src="<%= image_url('default_user.png') %>" alt="user">
          <% end %>
        </div>
        <div class="blog-detail">
          <div class="u_name">
            <%= link_to(blog.user.name, user_path(id: blog.user.username)) %>
          </div>
          <div class="blog-category">
            <%= link_to(blog.category.name, category_path(blog.category.slug)) %> 
            <span>&#8211;</span>
            <span class="f12"> <%= blog.updated_at.strftime('%b %d, %Y') %></span>
          </div>
        </div>
      </div>
      <div class="blog-desc">
        <% if blog.live? %>
          <%= link_to blog_show_path(id: blog, category_id: blog.category) do %>
            <div class="d-flex align-items-center justify-content-between mb-2">
              <h3 class="blog-title mb-0"><%= blog.title %></h3>
              <div class="blog-activity">
                <span class="mx-2"><%= blog.likes_count %> <i class="fas fa-heart fa-theme-red"></i></span>
                <span><%= blog.comments_count %> <i class="fas fa-comments dark-color"></i></span>
              </div>
            </div>
            <p class="mb-0 wb-bw"><%= raw blog.short_description %></p>
          <% end %>
        <% else %>
          <%= link_to edit_blog_path(blog.slug) do %>
            <h3><%= blog.title %></h3>
            <p class="mb-0 wb-bw"><%= raw blog.short_description %></p>
          <% end %>
        <% end %>
      </div>
    </div>
    <!-- end of .content-wrap -->
  <% end %>
  <div class="ml-lg-5">
    <%= paginate @blogs %>
  </div>
<% else %>
  <div class="content-wrap c-wrap text-center">
    <img src= "<%= image_url('no-content-found.svg') %>" width= "60%" height= "60%" loading="lazy">
    <div class="text-center" style="display: inline-block;">
      <span>No articles found </span>
      <% if current_user %>
        <%= link_to 'Write your Own', new_blog_path ,class: 'btn btn-bg mt-3 mb-3 btn-theme' %>
      <% else %>
        <%= link_to 'Write your Own', new_user_session_path ,class: 'btn btn-bg mt-3 mb-3 btn-theme' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/blogs/_comments.html.erb
<!-- <h3>Comments (<span class="comments-count"><%= @blog.comments_count %></span>)</h3> -->
<% if current_user %>
  <div class="mb-5 bg-white">
    <%= form_for(Comment.new, remote: true) do |form| %>
      <div class="my-3">
        <%= hidden_field_tag :blog_id, @blog.slug %>
        <%= form.text_area :body , class: "form-control redactor-comment", required: true %>
      </div>
      <%= form.submit 'Reply', class: 'btn btn-theme rounded-0 float-right' %>
    <% end %>
  </div>
<% else %>
  <div class="mb-5 border shadow p-4 bg-light text-dark border-corner overflow-hidden">
    <i class="fas fa-unlock-alt mr-2"></i>Sign In to add your thoughts...
    <a class="btn btn-outline-primary ml-3" href="<%= new_user_session_path %>">LogIn</a>
    <div class="disable-form-container mt-2">
      <div class="hidden-form"></div>
      <div class="disable-form">
        <div class="my-3">
          <%= text_area_tag :comment , "It's an Awesome article! ", class: "form-control", rows: "10"%>
        </div>
        <%= button_tag 'Reply', class: 'btn btn-theme rounded-0 float-right mr-3' %>
      </div>
    </div>
  </div>
<% end %>
<div class="mb-5 border shadow p-4 text-dark border-corner overflow-hidden <%= 'd-none' unless @comments.present? %>" id="comment-section">
  <div id="comments">  
    <% @comments.each do |comment| %>
      <%= render 'blogs/comments/show', comment: comment %>
    <% end %>
  </div>
</div>
<% unless @comments.present? %>
  <div class="mb-5 p-4 text-dark border-corner overflow-hidden text-center c-wrap" id="no-comment-image">
    <img src= "<%= image_url('no-comments-found.svg') %>" width= "60%" height= "60%" loading="lazy">
    <h5 class="pt-4">Be the first one to share your thoughts!</h5>
  </div>
<% end %>

app/views/blogs/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 order-md-2">
      <div class="mb-4 c-wrap pb-3 pt-3 px-3 blog-form-tags bg-white">
        <%= form_with(model: @blog, local: true) do |form| %>
          <% if @blog.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>
              <ul>
              <% @blog.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="my-3">
            <%= form.text_field :title, class: "form-control f14", required: true, placeholder:"Title", autocomplete:"off"%>
          </div>

          <div class="my-3">
            <%= form.text_area :description , class: "form-control redactor-textarea", placeholder: 'Share your knowledge', required: true %>
          </div>

          <div class="my-3">
            <label>Category</label>
            <%= form.select :category_id, options_for_select(get_categories, @blog.category_id), { prompt: '--Select Category--' }, class: "form-control custom-select select_two", required: true %>
          </div>

          <div class="my-3">
            <label>Tags</label>
            <%#= select_tag :tag_list, options_for_select(Tag.pluck(:name)), class: 'form-control custom-select tag-select select_two', multiple: true %>
            <%= form.text_field :tag_list, value: @blog.tags.pluck(:name).join(','), 'data-role': "tagsinput", class: "tag-select" %>
          </div>

          <div class="actions">
            <% if @blog.new_record? || @blog.draft? %>
              <%= form.submit 'Publish', class: 'btn btn-bg mt-4 mb-3 btn-theme' %>
              <%= form.button 'Save as Draft', value: true , type: :submit, name: "draft", data: {disable_with: "Please wait..."}, class: "btn btn-bg mt-4 mb-3 btn-theme ml-3" %>
            <% else %>
              <%= form.submit 'Update', class: 'btn btn-bg mt-4 mb-3 btn-theme' %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-1 order-md-1">
      <p class="text-center"></p>
    </div>
    <div class="col-md-3 order-md-3">
      <p class="text-center">Ads</p>
    </div>
  </div>
</div>

app/views/blogs/edit.html.erb
<%= stylesheet_link_tag 'blogs/new', media: 'all' %>

<%= render 'form', topic: @blog %>
<%= javascript_include_tag 'blogs/new' %>

app/views/blogs/index.html.erb
<% content_for :title, "Knowledge Gang" %>
<!-- banner -->
<!-- <div class="container-fluid bg-light py-5 shadow-sm mb-3">
  <div class="row">
    <div class="col-md-6 home-banner-padding home-banner-text">
      <div class="text-verticle-center">
        <h2 class="text-60">Share your knowledge</h2>
        <h6 class="pt-3">Share the Expertise, Knowledge and Stories of around the world with the society. You may share the Analysis, Trending News or story about Celebrities and Innovations going on around the world, Ancient Histories and many more.</h6>
        <h6>Every KNOWLEDGE is welcome.</h6>
      </div>
    </div>
    <div class="col-md-6 home-banner-padding text-center home-banner-image">
      <img src= "<%= image_url('knowledge-home.jpg') %>" loading="lazy">
    </div>
  </div>
</div> -->
<!-- end of banner -->
<div class="main-container">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10 px-0">
        <div class="c-wrap">
          <div class="swiper-container">
              <!-- Additional required wrapper -->
              <div class="swiper-wrapper">
                  <!-- Slides -->
                  <div class="swiper-slide skeleton">Trending</div>
                  <div class="swiper-slide skeleton">Trending</div>
                  <div class="swiper-slide skeleton">Trending</div>
              </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-lg-10">
        <div class="row justify-content-between">
          <div class="col-lg-8 px-0 pr-lg-3">
            <%= render 'blogs' %>
          </div>
          <div class="col-lg-4 px-0 pr-lg-0 pl-lg-3">
            <div class="right-sidenav bg-white c-border d-none d-lg-block">
              <div class="text-dark">
                <div class="d-flex align-items-center justify-content-between p-3 border-bottom">
                  <h2 class="category text-capitalize mb-0">Top Categories</h2>
                  <a href="#" class="btn btn-theme btn-sm rounded-0 f12">VIEW ALL</a>
                </div>
                <% @trending_categories.each do |category| %>
                  <%= link_to category_path(category.slug)do %>
                    <div class="category-wrap d-flex align-items-center justify-content-between">
                      <div class="d-flex align-items-center">
                        <div class="category-img"></div>
                        <span class="category-name"><%= category.name %></span>
                      </div>
                      <span class="category-count">
                        <i class="fas fa-newspaper mr-2"></i><%= category.blogs_count || 0 %>
                      </span>
                    </div>
                  <% end %>
                <% end %>
                <div class="p-3 border-top">
                  <div class="tag-wrap">
                    <% @home_tags.each do |tag_name, tag_detail| %>
                      <div class="tag mr-2 mb-2 btn btn-sm text-capitalize">
                        <%= link_to tag_path(tag_detail[:slug]) do %>
                          <i class="fa fa-tag mr-1"></i>
                          <%= tag_name %>
                        <% end %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class="footer">
              <div class="c-wrap mb-0 mt-3">
                <p class="mb-0 f12 text-center">Company &copy; 2021. All rights reserved
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/blogs/like.js.erb
<% if @errors %>

<% else %>
var hits = $(".hits-count").html();
$(".hits-count").html(parseInt(hits) + 1);
$('.like-side-blog').children('i').attr('class', 'fas fa-heart fa-lg fa-theme-red');
<% end %>

app/views/blogs/new.html.erb
<%= stylesheet_link_tag 'blogs/new', media: 'all' %>
<%= render 'form', topic: @blog %>

<%= javascript_include_tag 'blogs/new' %>

app/views/blogs/show.html.erb
<%= stylesheet_link_tag 'blogs/show', media: 'all' %>
<% content_for :title, @blog.title %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-10">
      <div class="row">
        <!-- commented like section -->
        <!-- <div class="col-md-3 order-md-1 d-none d-md-block">
          <div class="position-fixed mt-5 text-center ml-5">
            <p class="inline-para">
              <% if current_user %>
                <a href="javascript:void(0)" class="side-btn like-side-blog" data-blog-slug="<%= @blog.slug %>">
                  <% if current_user.liked_blog?(@blog) %>
                    <i class="fas fa-heart fa-lg fa-theme-red"></i> 
                  <% else %>
                    <i class="far fa-heart fa-lg"></i> 
                  <% end %>
                  <span class="hits-count"><%= @blog.likes_count %></span>
                </a>
              <% else %>
                <a href="<%= new_user_session_path %>" class="side-btn">
                  <i class="far fa-heart fa-lg"></i>
                  <span class="hits-count"><%= @blog.likes_count %></span>
                </a>
              <% end %>
            </p>
            <p class="inline-para">
              <a href="javascript:void(0)" class="side-btn" id="comment-side-blog" data-blog-slug="<%= @blog.slug %>"><i class="far fa-comments fa-lg"></i> <span class="comments-count"><%= @blog.comments_count %></span></a>
            </p>
            <p class="inline-para">
              <% if current_user %>
                <a href="javascript:void(0)" class="side-btn bookmark-side-blog" data-blog-slug="<%= @blog.slug %>">
                  <% if current_user.bookmarked?(@blog) %>
                    <i class="fas fa-bookmark fa-lg"></i>
                  <% else %>
                    <i class="far fa-bookmark fa-lg"></i>
                  <% end %>
                </a>
              <% else %>
                <a href="<%= new_user_session_path %>" class="side-btn">
                  <i class="far fa-bookmark fa-lg"></i>
                </a>
              <% end %>
            </p>
          </div>
        </div>
        -->
        <div class="col-md-8">
          <div class="mb-5 description-container bg-white c-wrap text-justify mb-4 p-4 text-dark">
            <% if @blog.user == current_user %>
              <div class="float-right">
                <%= link_to edit_blog_path(@blog.slug) do %>
                  <i class="fas fa-edit" aria-hidden="true"></i>
                <% end %>
              </div>
            <% end %>
            <h1 class="text-center mb-5 mt-4"><strong><%= @blog.title %></strong></h1>
            <%= @blog.description.gsub("<table>","<table class='table table-bordered'>").html_safe %>
            <h3>Category: <%= link_to @blog.category.name, category_path(@blog.category) %></h3>
            <p class="mt-3">Tags: <%= raw @blog.taggings.map { |t| link_to t.tag.name, tag_path(t.tag.slug) }.join(', ') %></p>
    
            <%#= link_to 'Edit', edit_blog_path(@blog),class: "btn btn-outline-info btn-sm" %>
            <div class="bottom-actions mb-3 mt-5">
              <p class="inline-para">
                <% if current_user %>
                  <a href="javascript:void(0)" class="side-btn like-side-blog" data-blog-slug="<%= @blog.slug %>">
                    <% if current_user.liked_blog?(@blog) %>
                      <i class="fas fa-heart fa-lg fa-theme-red"></i> 
                    <% else %>
                      <i class="far fa-heart fa-lg"></i> 
                    <% end %>
                    <span class="hits-count"><%= @blog.likes_count %></span> <span>Likes</span>
                  </a>
                <% else %>
                  <a href="<%= new_user_session_path %>" class="side-btn">
                    <i class="far fa-heart fa-lg"></i>
                    <span class="hits-count"><%= @blog.likes_count %></span> <span>Likes</span>
                  </a>
                <% end %>
              </p>
              <p class="inline-para">
                <a href="javascript:void(0)" class="side-btn comment-side-blog" data-blog-slug="<%= @blog.slug %>">
                  <i class="far fa-comments fa-lg"></i>
                  <span class="comments-count"><%= @blog.comments_count %></span> <span>Comments</span>
                </a>
              </p>
              <p class="inline-para">
                <% if current_user %>
                  <a href="javascript:void(0)" class="side-btn bookmark-side-blog" data-blog-slug="<%= @blog.slug %>">
                    <% if current_user.bookmarked?(@blog) %>
                      <i class="fas fa-bookmark fa-lg"></i> <span class="read-it-later">Saved</span>
                    <% else %>
                      <i class="far fa-bookmark fa-lg"></i> <span class="read-it-later">Read it Later!</span>
                    <% end %>
                  </a>
                <% else %>
                  <a href="<%= new_user_session_path %>" class="side-btn" >
                    <i class="far fa-bookmark fa-lg"></i> <span class="read-it-later">Read it Later!</span>
                  </a>
                <% end %>
              </p>
              <div class="inline-para float-right">
                <% blog_url = blog_show_url(id: @blog, category_id: @blog.category) %>
                <span class="dinline">
                  <%= link_to "<i class='fab fa-facebook fa-lg'></i>".html_safe, "http://www.facebook.com/share.php?quote=#{@blog.title}&u=#{blog_url}" , class: "share zin-fb offer-share-link", rel: "nofollow", target: 'blank', title: "Facebook" %>
                </span>
                <span class="dinline">  
                  <%= link_to "<i class='fab fa-twitter fa-lg'></i>".html_safe, "https://twitter.com/intent/tweet?text=#{@blog.title} #{blog_url}" , class: "share zin-tw offer-share-link", rel: "nofollow", target: 'blank', title: "Twitter" %>
                </span>
                <span class="dinline">
                  <%= link_to "<i class='fab fa-whatsapp fa-lg'></i>".html_safe, "https://api.whatsapp.com/send?text= #{@blog.title} #{blog_url}." , rel: 'nofollow', title: "Whatsapp", target: 'blank', class: "share zin-wa offer-share-link" %>
                </span>
                <span class="dinline">
                  <%= link_to "<i class='fab fa-telegram fa-lg'></i>".html_safe, "https://t.me/share/url?url=#{blog_url}" , rel: 'nofollow', title: "Telegram", class: "share zin-tw offer-share-link", target: 'blank' %>
                </span>
              </div>
            </div>
            <%= render 'comments' %>
          </div>
          
        </div>
        <div class="col-md-4">
          <p class="text-center">tags list/ Ads</p>
        </div>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag 'blogs/show' %>