config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  root to: 'blogs#index'
  resources :blogs, except: [:show] do
    member do
      post 'like'
      post 'bookmark' => 'users#bookmark'
    end
  end
  resources :comments
  resources :tags
  get 'tags-name-list' => 'tags#name_list'
  get '/trending' => 'home#trending', as: 'trending'
  get '/search' => 'home#search', as: 'search'
  resources :categories
  post '/follow_update' => 'followers#follow_update'
  devise_for :users, :controllers => {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "sessions",
    registrations: "registrations"
  }
  get '/bookmarked-articles' => 'users#bookmarked', as: 'bookmarked_articles'
  resources :users, only: [:show, :edit, :update] do
    member do
      put 'update_username'
      get 'comments'
      get 'following/suggestions' => 'users#following_suggestions', as: 'follow_suggestions'
      get 'following/categories' => 'users#following_categories', as: 'follow_categories'
      get 'following/people' => 'users#following_people', as: 'follow_people'
      get 'following/tags' => 'users#following_tags', as: 'follow_tags'
    end
  end
  get '/:category_id/:id' => 'blogs#show', as: 'blog_show'
  post '/image_upload' => 'attachments#image_upload'
end

app/models/user.rb
class User < ApplicationRecord

  include Searchable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  belongs_to :country, optional: true
  has_many :blogs
  has_many :likes
  has_many :comments
  has_many :bookmarks
  has_many :bookmarked_blogs, through: :bookmarks, source: :blog
  has_many :followers, as: :followable
  has_many :taggings
  has_many :tags, through: :taggings

  validates :username, :email, uniqueness: true, allow_nil: true

  after_create :set_username

  before_save :reindex_blogs, if: proc {|user| user.name_changed? || user.username_changed?}

  enum status: { active: 1, pending: 2 }

  mount_uploader :avatar, ImageUploader

  def as_indexed_json(options = {})
    self.as_json(
      only: [:username, :name, :blogs_count]
    )
  end

  def following_users
    Follower.where(user_id: id, followable_type: 'User')
  end

  def following_tags
    Follower.where(user_id: id, followable_type: 'Tag')
  end

  def following_categories
    Follower.where(user_id: id, followable_type: 'Category')
  end

  def liked_blog?(blog)
    likes.where(blog: blog).exists?
  end

  def bookmarked?(blog)
    bookmarks.where(blog: blog, active: true).exists?
  end

  def following?(resource)
    send("following_#{resource.class.table_name}").where(followable_id: resource.id).exists?
  end

  def admin?
    false #self.is_admin
  end

  def set_username
    user_name = ''
    loop do
      user_name = (email.split("@").first.gsub(".","") + rand(999).to_s)
      break user_name unless User.where(username: user_name).exists?
    end
    self.update_column(:username, user_name)
  end

  def top_tags
    self.tags.select('tags.id,tags.name,tags.slug,count(taggings.tag_id) as count').group('tags.id,taggings.tag_id,tags.name,tags.slug').to_a.sort_by(&:count).reverse
  end

  def people_suggestion_on_category(already_following_users)
    categories_follow = self.following_categories
    users_suggestions = {}
    if categories_follow.count > 1
      # N+1 Query is here Danger !!!
      categories_follow.each do |category_follow|
        curr_category = category_follow.followable
        users_suggestions["#{curr_category.name}"] = User.joins(:blogs).where(blogs: {category_id: curr_category.id}).distinct - already_following_users
      end
    elsif categories_follow.count == 1
      curr_category = categories_follow.first.followable
      users_suggestions["#{curr_category.name}"] = User.joins(:blogs).where(blogs: {category_id: curr_category.id}).distinct - already_following_users
    else
      curr_category = Category.first
      users_suggestions["#{curr_category.name}"] = User.joins(:blogs).where(blogs: {category_id: curr_category.id}).distinct - already_following_users
    end
    users_suggestions.reject!{|k,v| v.count == 0}
  end

  def reindex_blogs
    blogs.each do |blog|
      blog.es_reindex
    end
  end

  class << self
    def new_with_session(params, session)
      super.tap do |user|
        if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank?
        end
        if data = session["devise.google_oauth2"] && session["devise.google_oauth2_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank?
        end
      end
    end

    def from_omniauth(auth)
      user = where(provider: auth.provider, uid: auth.uid).first_or_initialize
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      # user.avatar = auth.provider == 'facebook' ? auth.info.image + '&type=normal' : auth.info.image
      user.status = User.statuses[:active] if user.pending?
      user.skip_confirmation! if user.new_record?
      user.save!
      user
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
    else
      session["devise.google_oauth2_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :update_username, :comments, :following_suggestions, :following_categories, :following_people, :following_tags]
  before_action :authenticate_user!, only: [:bookmarked, :edit, :update,:bookmark, :update_username, :following_suggestions, :following_categories, :following_people, :following_tags]
  before_action :authenticate_access, only: [:edit, :update, :update_username, :following_suggestions, :following_categories, :following_people, :following_tags]

  def show
    blog_status = params[:status] == 'draft' ? 0 : 1
    @blogs = Blog.unscoped.where(user: @user, status: blog_status).page(params[:page]).per(12)
    @top_tags = @user.top_tags
    @follow_action = current_user&.following?(@user) ? 'unfollow' : 'follow'
    @followable_type = 'User'
    @followable_id = @user.id
  end

  def comments
    @comments = @user.comments.order(id: :desc)
    @top_tags = @user.top_tags
    @follow_action = current_user&.following?(@user) ? 'unfollow' : 'follow'
    @followable_type = 'User'
    @followable_id = @user.id
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to user_path(@user.username)
    else
      render 'edit'
    end
  end

  def update_username
    if @user.update_attributes(user_params)
      redirect_to edit_user_path(@user.username)
    else
      @error = @user.errors.full_messages.first
      respond_to do |format|
        format.js
      end
    end
  end
  
  def bookmark
    if blog = Blog.find_by(slug: params[:id])
      @bookmark = current_user.bookmarks.find_or_initialize_by(blog: blog)
      @bookmark.active = !@bookmark.active?
      @bookmark.save
    else
      render file: 'public/404', status: :not_found, layout: true
    end
  end

  def bookmarked
    @blogs = Blog.includes(:category).where(id: current_user.bookmarks.active.pluck(:blog_id)).page(params[:page]).per(12)
  end

  def following_suggestions
    # N+1 Query, need to handle includes for polymorphic association
    @following_people = User.joins(:followers).where(followers: {followable_type: 'User',  user_id: current_user.id}).distinct.first(5)
    @following_tags = Tag.joins(:followers).where(followers: {followable_type: 'Tag',  user_id: current_user.id}).distinct.first(5)
    @suggested_users = current_user.people_suggestion_on_category(@following_people)
  end

  def following_categories
    @categories = Category.all
  end

  def following_people
    @following_people = User.joins(:followers).where(followers: {followable_type: 'User',  user_id: current_user.id}).distinct.page(params[:page]).per(20)
  end

  def following_tags
    @following_tags = Tag.joins(:followers).includes(:taggings).where(followers: {followable_type: 'Tag',  user_id: current_user.id}).distinct.page(params[:page]).per(20)
  end

  private

  def user_params
    params.require(:user).permit(:id, :name, :bio, :birth_date, :country_id, :mobile_number, :username, :avatar)
  end

  def set_user
    unless @user = User.find_by(username: params[:id])
      render file: 'public/404', status: :not_found, layout: true
    end
  end

  def authenticate_access
    render :file => 'public/404', status: 401 unless @user == current_user
  end

end

app/views/users/_following_tab.html.erb
<div class="container">
  <div class="justify-content-center">
    <div class="px-lg-0">
        <nav class="nav nav-pills nav-justified border-corner bg-white">
            <% suggestions_active = tab_selected == 0 ? 'active' : ''%>
            <% categories_active = tab_selected == 1 ? 'active' : ''%>
            <% people_active = tab_selected == 2 ? 'active' : ''%>
            <% tags_active = tab_selected == 3 ? 'active' : ''%>
            <a href="<%= follow_suggestions_user_path(@user.username) %>" class="nav-item nav-link border rounded-0 font-weight-bold <%= suggestions_active %>">Suggestions</a>
            <a href="<%= follow_categories_user_path(@user.username) %>" class="nav-item nav-link border rounded-0 font-weight-bold <%= categories_active %>">Categories</a>
            <a href="<%= follow_people_user_path(@user.username) %>" class="nav-item nav-link border rounded-0 font-weight-bold <%= people_active %>">People</a>
            <a href="<%= follow_tags_user_path(@user.username) %>" class="nav-item nav-link border rounded-0 font-weight-bold <%= tags_active %>">Tags</a>
        </nav>
    </div>
  </div>
  
</div>

app/views/users/_form.html.erb
<!-- Note: Avatar is pending -->
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 ml-lg-5">
      <h4 class="mb-3 text-center">Update Profile</h4>
      <div class="mb-4 border border-light pb-3 pt-3 px-3 shadow border-corner">
        <%= form_for(@user, url: user_path(@user.username), method: :patch) do |form| %>
          <% if @user.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

              <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="my-3">
            <label>Name</label>
            <%= form.text_field :name, class: "form-control", required: true %>
          </div>

          <div class="my-3">
            <label>Bio</label>
            <%= form.text_area :bio , class: "form-control", placeholder: 'Share about yourself...', rows: 5 %>
          </div>

          <div class="my-3">
            <label>Birth Date</label>
            <%= form.date_field :birth_date, class: "form-control datepicker" %>
          </div>

          <div class="my-3">
            <label>Mobile Number</label>
            <%= form.text_field :mobile_number, class: "form-control" %>
          </div>

          <div class="my-3">
            <label>Country</label>
            <%= form.select :country_id, options_for_select(get_countries, @user.country_id), { prompt: '--Select Country--' }, class: "form-control custom-select select_two" %>
          </div>

          <div class="actions">
            <%= form.submit 'Update Profile', class: 'btn btn-bg mt-4 mb-3 btn-theme' %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="user-form-avatar border border-light shadow border-corner text-center mt-5">
        <div class="pt-2">
          <% if @user.avatar.present? %>
            <%= cl_image_tag(@user.avatar, :secure=>true, :transformation=>[], :class => 'rounded-circle') %>
          <% else %>
            <img class="rounded-circle" src="<%= image_url('default_user.png') %>">
          <% end %>
        </div>
        <div class="pt-2">
          <h5 class=""><%= @user.name %></h5>
          <p class="">@<%= @user.username %>
          </p>
        </div>
        <div class="pb-3">
          <%= link_to 'javascript:void(0)', 'data-toggle'=>"modal", "data-target"=>"#updateUsername" do %>
            <i class="fas fa-edit"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="updateUsername" tabindex="-1" role="dialog" aria-labelledby="updateUsernameLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="background: white!important;">
      <div class="modal-header">
        <h5 class="modal-title" id="updateUsernameLabel">Update Username</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for(@user, url: update_username_user_path(@user.username), method: :put, remote: true) do |form| %>
        <div class="modal-body">
          <div class="form-group">
            <label for="username" class="col-form-label">Username:</label>
            <%= form.text_field :username, class: 'form-control' %>
            <span class="error"></span>
          </div>
          <div class="form-group">
            <label for="avatar" class="col-form-label">Profile Picture:</label>
            <%= form.file_field :avatar, class: 'form-control' %>
            <span class="error"></span>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= form.submit 'Update', class: 'btn btn-theme' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/comments.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-10 px-lg-0">
      <div class="row user-profile">
        <div class="col-md-9">
          <div class="c-wrap mb-3 p-4">
            <div class="row align-items-center">
              <div class="col-md-2 text-center">
                <% if @user.avatar.present? %>
                  <img src="<%= @user.avatar %>" class="rounded-circle card-img-top mb-2" alt="user">
                <% else %>
                  <img class="card-img-top rounded-circle mb-2" src="<%= image_url('default_user.png') %>" alt="user">
                <% end %>
                <% if current_user&.id != @user.id %>
                  <div id="follow-container" class="user-show-follow">
                    <%= render 'followers/follow_action' %>
                  </div>
                <% end %>
              </div>
              <div class="col-md-10 user-detail-profile">
                <div id="user-show">
                  <div class="username-profile user-show-profile"><span class="text-20"><b><%= @user.name || @user.username %></b></span></div>
                </div>
                <p class="text-15 text-capitalize"> writer since <%= @user.created_at.strftime("%B, %Y") %></p>
                <div class="mt-1 bio-text">
                  <i class="fas fa-quote-left mr-3"></i><%= @user.bio %><i class="fas fa-quote-right ml-3"></i>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <!-- channel info -->
          <div class="c-wrap p-3">
            <h4 class="pb-3 font-weight-bold border-bottom">Channel Information</h4>
            <div class="row mb-0">
              <div class="col-12">
                <div class="d-flex">
                  <dt class="col px-0">Bookmark Posts</dt>
                  <dd>50</dd>
                </div>
                <div class="d-flex">
                  <dt class="col px-0">Like</dt>
                  <dd>1.14B</dd>
                </div>
                <div class="d-flex">
                  <dt class="col px-0">Comments</dt>
                  <dd>5M</dd>
                </div>
              </div>
            </div>
          </div>
          <!-- channel info -->
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-10 px-lg-0">
      <div class="row">
        <div class="col-md-9 mb-5 user-articles">
          <nav class="nav nav-pills nav-justified border-corner bg-white">
            <% live_blog_active = action_name == 'show' && params[:status] != 'draft' ? 'active' : ''%>
              <% draft_active = action_name == 'show' && params[:status] == 'draft' ? 'active' : ''%>
              <% comments_active = action_name == 'comments' ? 'active' : ''%>
              <a href="<%= user_path(@user.username) %>" class="nav-item nav-link border rounded-0 font-weight-bold <%= live_blog_active %>">Published Articles</a>
              <% if current_user == @user %>
                <a href="<%= user_path(@user.username, status: 'draft') %>" class="nav-item nav-link border rounded-0 font-weight-bold <%= draft_active %>">Drafts</a>
              <% end %>
              <a href="<%= comments_user_path(@user.username) %>" class="nav-item nav-link border rounded-0 font-weight-bold <%= comments_active %>">Comments</a>
          </nav>
          <% if @comments.present? %>
            <div class="mb-5 border shadow p-4 ml-lg-5  text-dark border-corner overflow-hidden">
              <div id="comments">
                <% @comments.each do |comment| %>
                  <%= render 'blogs/comments/show', comment: comment %>
                <% end %>
              </div>
            </div>
          <% else %>
            <div class="mb-5 p-4 text-dark border-corner overflow-hidden text-center c-wrap" id="no-comment-image">
              <img src= "<%= image_url('no-comments-found.svg') %>" width= "60%" height= "60%" loading="lazy">
            </div>
          <% end %>
        </div>
        <div class="col-md-3">
          <div class="mb-4 text-dark mt-5">
            <h5 class="mb-3"><b>Top tags:</b></h5>
            <% if @top_tags.present? %>
              <% @top_tags.each do |tag| %>
                <%= link_to tag_path(tag.slug) do %>
                  <button type="button" class="btn btn-theme mr-2 mb-2">
                    <%= tag.name %> <span class="badge badge-light"><%= tag.count %></span>
                  </button>
                <% end %>
              <% end %>
            <% else %>
              <h6 class="mb-3 pl-3"><i class="fas fa-tag mr-2"></i>No tags used</h6>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% content_for :title, "Edit Profile" %>
<div class="container-fluid">
  <%= render 'form' %>
</div>

app/views/users/following_categories.html.erb
<%= render 'following_header' , tab_selected: 1 %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-10 px-lg-0">
      <div class="row">
        <div class="col-md-9 mb-5">
          <div class="mb-4 text-dark mt-5">
            <div class="card-columns">
              <% @categories.each do |category| %>
                <div class="card">
                  <div class="card-block p-2">
                    <div class="mb-2">
                      <%= link_to category_path(category.slug) do %>
                        <p class="card-title"><b><%= category.name %></b></p>
                        Total Articles: <b><%= category.blogs_count %></b>
                      <% end %>
                    </div>
                    <%= render 'list_follow_btn', entity: category %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="mb-4 text-dark mt-5">
            <h5 class="mb-3">
            <b>Google Ads</b>
          </div>
          <div class="mb-4 text-dark mt-5">
            <h5 class="mb-3">
            <b>Google Ads</b>
          </div>
        </div>
      </div>
    </div>
  </div>
  
</div>

app/views/users/following_suggestions.html.erb
<%= render 'following_header', tab_selected: 0 %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-10 px-lg-0">
      <div class="row">
        <div class="col-md-9 mb-5">
            <div class="mb-4 text-dark mt-5">
                <% @suggested_users.each do |category_name, users_list| %>
                    <div class="mb-5">
                        <p><b>Authors writing about <%= category_name %></b></p>
                        <% users_list.each do |user| %>
                            <div class="mb-2">
                                <% if user.avatar.present? %>
                                    <img src="<%= user.avatar %>" class="rounded-circle user-img-44 mr-2" alt="user">
                                <% else %>
                                    <img class="user-img-44 rounded-circle mr-2" src="<%= image_url('default_user.png') %>" alt="user">
                                <% end %>
                                <%= link_to user_path(user.username) do %>
                                    <%= user.username %>
                                <% end %>
                                <p>Article writer on "<%= category_name %>"</p>
                            </div>
                            <%= render 'list_follow_btn', entity: user %>
                        <% end %>
                    </div>
                    <hr size="10">
                <% end %>
            </div>
        </div>
        <div class="col-md-3">
          <div class="mb-4 text-dark mt-5">
            <h5 class="mb-3">
            <b>People you follow</b>
            <a class="pl-3" href="<%= follow_people_user_path(current_user.username) %>">See all</a>
            </h5>
            <% if @following_people.present? %>
              <% @following_people.each do |people| %>
                <div class="mb-2">
                    <% if people.avatar.present? %>
                        <img src="<%= people.avatar %>" class="rounded-circle user-img-30 mr-2" alt="user">
                    <% else %>
                        <img class="user-img-30 rounded-circle mr-2" src="<%= image_url('default_user.png') %>" alt="user">
                    <% end %>
                    <%= link_to user_path(people.username) do %>
                        <%= people.username %>
                    <% end %>
                </div>
                <%= render 'list_follow_btn', entity: people %>
                <hr>
              <% end %>
            <% else %>
              <h5 class="mb-3 pl-3"><i class="fas fa-tag mr-2"></i>You are not following to any one...</h5>
            <% end %>
          </div>

          <div class="mb-4 text-dark mt-5">
            <h5 class="mb-3">
            <b>Tags you follow</b>
            <a class="pl-3" href="<%= follow_tags_user_path(current_user.username) %>">See all</a>
            </h5>
            <% if @following_tags.present? %>
              <% @following_tags.each do |tag| %>
                <div class="mb-2">
                    <%= link_to tag_path(tag.slug) do %>
                        <b><i class="fa fa-tag mr-1"></i><%= tag.name %></b>
                    <% end %>
                </div>
                <%= render 'list_follow_btn', entity: tag %>
                <hr>
              <% end %>
            <% else %>
              <h5 class="mb-3 pl-3"><i class="fas fa-tag mr-2"></i>You are not following to any one...</h5>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  
</div>

app/views/users/following_tags.html.erb
<%= render 'following_header', tab_selected: 3 %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-10 px-lg-0">
      <div class="row">
        <div class="col-md-9 mb-5">
          <div class="mb-4 text-dark mt-5">
            <div class="card-columns">
              <% @following_tags.each do |tag| %>
                <div class="card">
                  <div class="card-block p-2">
                    <div class="mb-2">
                      <%= link_to tag_path(tag.slug) do %>
                        <p class="card-title"><i class="fa fa-tag mr-1"></i><b><%= tag.name %></b></p>
                        Total Articles: <b><%= tag.taggings.count %></b>
                      <% end %>
                    </div>
                    <%= render 'list_follow_btn', entity: tag %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <div class="">
            <%= paginate @following_tags %>
          </div>
        </div>
        <div class="col-md-3">
          <div class="mb-4 text-dark mt-5">
            <h5 class="mb-3">
            <b>Google Ads</b>
          </div>
          <div class="mb-4 text-dark mt-5">
            <h5 class="mb-3">
            <b>Google Ads</b>
          </div>
        </div>
      </div>
    </div>
  </div>
  
</div>

app/views/users/show.html.erb
<% content_for :title, @user.name || @user.username %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-10 px-lg-0">
      <div class="row user-profile">
        <div class="col-md-9">
          <div class="c-wrap mb-3 p-4">
            <div class="row align-items-center">
              <div class="col-md-2 text-center">
                <% if @user.avatar.present? %>
                  <img src="<%= @user.avatar %>" class="rounded-circle card-img-top mb-2" alt="user">
                <% else %>
                  <img class="card-img-top rounded-circle mb-2" src="<%= image_url('default_user.png') %>" alt="user">
                <% end %>
                <% if current_user&.id != @user.id %>
                  <div id="follow-container" class="user-show-follow">
                    <%= render 'followers/follow_action' %>
                  </div>
                <% end %>
              </div>
              <div class="col-md-10 user-detail-profile">
                <div id="user-show">
                  <div class="username-profile user-show-profile"><span class="text-20"><b><%= @user.name || @user.username %></b></span></div>
                </div>
                <p class="text-15 text-capitalize"> writer since <%= @user.created_at.strftime("%B, %Y") %></p>
                <div class="mt-1 bio-text">
                  <i class="fas fa-quote-left mr-3"></i><%= @user.bio %><i class="fas fa-quote-right ml-3"></i>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <!-- channel info -->
          <div class="c-wrap p-3">
            <h4 class="pb-3 font-weight-bold border-bottom">Channel Information</h4>
            <div class="row mb-0">
              <div class="col-12">
                <div class="d-flex">
                  <dt class="col px-0">Bookmark Posts</dt>
                  <dd>50</dd>
                </div>
                <div class="d-flex">
                  <dt class="col px-0">Like</dt>
                  <dd>1.14B</dd>
                </div>
                <div class="d-flex">
                  <dt class="col px-0">Comments</dt>
                  <dd>5M</dd>
                </div>
              </div>
            </div>
          </div>
          <!-- channel info -->
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-10 px-lg-0">
      <div class="row">
        <div class="col-md-9 mb-5 user-articles">
            <nav class="nav nav-pills nav-justified border-corner bg-white">
              <% live_blog_active = action_name == 'show' && params[:status] != 'draft' ? 'active' : ''%>
              <% draft_active = action_name == 'show' && params[:status] == 'draft' ? 'active' : ''%>
              <% comments_active = action_name == 'comments' ? 'active' : ''%>
              <a href="<%= user_path(@user.username) %>" class="nav-item nav-link border rounded-0 font-weight-bold <%= live_blog_active %>">Published Articles</a>
              <% if current_user == @user %>
                <a href="<%= user_path(@user.username, status: 'draft') %>" class="nav-item nav-link border rounded-0 font-weight-bold <%= draft_active %>">Drafts</a>
              <% end %>
              <a href="<%= comments_user_path(@user.username) %>" class="nav-item nav-link border rounded-0 font-weight-bold <%= comments_active %>">Comments</a>
            </nav>
            <%= render 'blogs/blogs' %>
        </div>
        <div class="col-md-3">
          <div class="mb-4 text-dark mt-5">
            <h5 class="mb-3"><b>Top tags:</b></h5>
            <% if @top_tags.present? %>
              <% @top_tags.each do |tag| %>
                <%= link_to tag_path(tag.slug) do %>
                  <button type="button" class="btn btn-theme tags-hover mr-2 mb-2">
                    <%= tag.name %> <span class="badge badge-light"><%= tag.count %></span>
                  </button>
                <% end %>
              <% end %>
            <% else %>
              <h6 class="mb-3 pl-3"><i class="fas fa-tag mr-2"></i>No tags used</h6>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  
</div>

app/views/users/update_username.js.erb
$('.error').html('<%= @error %>');