config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  root to: 'blogs#index'
  resources :blogs, except: [:show] do
    member do
      post 'like'
      post 'bookmark' => 'users#bookmark'
    end
  end
  resources :comments
  resources :tags
  get 'tags-name-list' => 'tags#name_list'
  get '/trending' => 'home#trending', as: 'trending'
  get '/search' => 'home#search', as: 'search'
  resources :categories
  post '/follow_update' => 'followers#follow_update'
  devise_for :users, :controllers => {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "sessions",
    registrations: "registrations"
  }
  get '/bookmarked-articles' => 'users#bookmarked', as: 'bookmarked_articles'
  resources :users, only: [:show, :edit, :update] do
    member do
      put 'update_username'
      get 'comments'
      get 'following/suggestions' => 'users#following_suggestions', as: 'follow_suggestions'
      get 'following/categories' => 'users#following_categories', as: 'follow_categories'
      get 'following/people' => 'users#following_people', as: 'follow_people'
      get 'following/tags' => 'users#following_tags', as: 'follow_tags'
    end
  end
  get '/:category_id/:id' => 'blogs#show', as: 'blog_show'
  post '/image_upload' => 'attachments#image_upload'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def trending
    #Need to change logic here for trending users etc
    @trending_tags = Tagging.trending_tags_with_count
    @trending_users = User.includes(:blogs).first(5)
    @blogs = Blog.trending_blogs.page(params[:page]).per(12)
  end

  def search
    @tags = Tag.__elasticsearch__.search(
      {
        query: {
          query_string: {
            query: "*#{params[:q]}*",
            fields: ['name', 'slug']
          }
        },
      }
    )
    # @categories = Category.__elasticsearch__.search(
    #   {
    #     query: {
    #       query_string: {
    #         query: "*#{params[:q]}*",
    #         fields: ['name', 'slug']
    #       }
    #     },
    #   }
    # )
    @articles = Blog.__elasticsearch__.search(
      {
        query: {
          query_string: {
            query: "*#{params[:q]}*",
            fields: ['title^10', 'description', 'slug']
          }
        },
      }
    )
    @users = User.__elasticsearch__.search(
      {
        query: {
          query_string: {
            query: "*#{params[:q]}*",
            fields: ['name', 'username']
          }
        },
      }
    )

    respond_to do |format|
      format.html {
        unless params[:type]
          @users = @users.limit(5)
          @articles = @articles.limit(10)
        end
        if params[:type] == 'users'
          @users = @users.page(params[:page]).per(12)
          render 'search_users'
        elsif params[:type] == 'blogs'
          @articles = @articles.page(params[:page]).per(12)
          render 'search_blogs'
        end
      }
      format.json {
        @tags = @tags.limit(5)
        # @categories = @categories.limit(5)
        @articles = @articles.limit(5)
        @users = @users.limit(5)
      }
    end
  end

  def search_users
    puts params[:query]
    #Need to change logic here for search
    @searched_users = User.includes(:blogs).first(5)
  end

  def search_tags
    puts params[:query]
    #Need to change logic here for search
    @searched_tags = Tag.last(5)
  end

  def search_blogs
    puts params[:query]
    #Need to change logic here for search
    @blogs = Blog.last(5)
  end

end

app/views/home/_blog_no_articles.html.erb
<div class="ml-lg-5 mb-4 p-4 text-dark border-corner text-center">
  <img src= "<%= image_url('no-content-found.svg') %>" width= "60%" height= "60%" loading="lazy">
  <div class="text-center" style="display: inline-block;">
    <span>No articles found </span>
    <% if current_user %>
      <%= link_to 'Write your Own', new_blog_path ,class: 'btn btn-bg mt-3 mb-3 btn-theme' %>
    <% else %>
      <a href="<%= new_user_session_path %>" class="btn btn-bg mt-3 mb-3 btn-theme">Write your Own</a>
    <% end %>
  </div>
</div>

app/views/home/_search_blog.html.erb
<% if ((index + 1) % 4 == 0) %>
  <div class="border shadow ml-lg-5 mb-4 p-4 text-dark border-corner">
    <div>google ad</div>
  </div>
<% end %>
<div class="border shadow ml-lg-5 mb-4 p-4 text-dark border-corner content-inside">
  <div><%= link_to(blog.user_name, user_path(id: blog.user_username)) %> in <%= link_to(blog.category_name, category_path(blog.category_slug)) %></div>
  <%= link_to blog_show_path(id: blog.slug, category_id: blog.category_slug) do %>
    <h4><%= blog.title %></h4>
    <p class="mt-3 wb-bw"><%= raw blog.short_description %></p>
  <% end %>
  <p class="mt-3 inline-para"><%= blog.updated_at.to_time.strftime('%b %d, %Y') %></p>
  <p class="mt-3 inline-para"><%= blog.likes_count %> <i class="fas fa-heart fa-theme-red"></i></p>
  <p class="mt-3 inline-para"><%= blog.comments_count %> <i class="fas fa-comments"></i></p>
</div>

app/views/home/_search_user.html.erb
<div class="col-md-3">
  <%= link_to user_path(id: user.username) do %>
    <div class="card card-block trending-card">
      <div class="card-image pt-3">
        <% if user.avatar.present? %>
          <img src="<%= user.avatar %>" class="rounded-circle" alt="user">
        <% else %>
          <img class="card-img-top" src="<%= image_url('default_user.png') %>" alt="user">
        <% end %>
      </div>
      <div class="card-body">
        <h5 class="card-title text-center two-line-text"><%= user.name %></h5>
        <p class="card-text"><%= user.username %></p>
        <p class="card-text"><b><%= user.blogs_count %></b> Articles published</p>
      </div>
    </div>
  <% end %>
</div>

app/views/home/search.html.erb
<% content_for :title, 'Search' %>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-9 mb-5">
      <% if @users.present? %>
        <div class="mb-5 ml-lg-3 overflow-hidden">
          <h5 class="mb-3"><b>Searched Users</b></h5>
          <div class="row flex-row flex-nowrap trending-users">
            <% @users.each do |user| %>
              <%= render 'search_user', user: user %>
            <% end %>
          </div>
        </div>
        <% if @users.count > 4 %>
          <%= link_to search_path(q: params[:q], type: 'users'), class: "btn btn-outline-success follow-btn" do %>
            More users search results →
          <% end %>
        <% end %>
        <hr>
      <% end %>
      <h5 class="mb-3 ml-lg-3"><b>Searched Articles</b></h5>
      <% if @articles.present? %>
        <% @articles.each_with_index do |blog, index| %>
          <%= render 'search_blog', blog: blog, index: index%>
        <% end %>
        <% if @articles.count > 10 %>
          <%= link_to search_path(q: params[:q], type: 'blogs'), class: "btn btn-outline-success follow-btn" do %>
            More Articles search results →
          <% end %>
        <% end %>
      <% else %>
        <%= render 'blog_no_articles' %>
      <% end %>
    </div>
    <div class="col-md-3">
      <div class="border shadow p-4 mr-lg-3 text-dark border-corner">
        <h5 class="mb-3"><b>Searched tags</b></h5>
        <% if @tags.present? %>
          <div class="tags-div">
            <% @tags.each do |tag| %>
              <%= link_to tag_path(tag.slug) do %>
                <button type="button" class="btn btn-theme mr-2 mb-2 tags-hover">
                  <b><%= tag.name %> <span class="badge badge-light"><%= tag.count %></span></b>
                </button>
              <% end %>
            <% end %>
          </div>
          <!-- <div class="tags-load-more text-center"> -->
            <%#= link_to 'javascript:void(0)', class: 'btn btn-outline-success follow-btn' do %>
              <!-- <i class="fas fa-plus-circle"></i> -->
            <!-- <%# end %> -->
          <!-- </div> -->
        <% else %>
          <i class="fas fa-tag mr-2"></i><span>No Tags found </span>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/search_blogs.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-9 mb-5">
      <h5 class="mb-3 ml-lg-3"><b>Searched Articles</b></h5>
      <% if @articles.present? %>
        <% @articles.each_with_index do |blog, index| %>
          <%= render 'search_blog', blog: blog, index: index%>
        <% end %>
        <div class="ml-lg-5 float-right">
          <%= paginate @articles %>
        </div>
      <% else %>
        <%= render 'blog_no_articles' %>
      <% end %>
    </div>
    <div class="col-md-3">
      <div class="mb-4 text-dark">
        <h5 class="mb-3"><b>Ads will be here!</b></h5>
      </div>
    </div>
  </div>
</div>

app/views/home/search_users.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-9 mb-5">
      <% if @users.present? %>
        <div class="mb-5 ml-lg-3 overflow-hidden">
          <h5 class="mb-3"><b>Searched Users</b></h5>
          <div class="row flex-row flex-nowrap trending-users">
            <% @users.each do |user|%>
              <%= render 'search_user', user: user %>
            <% end %>
            <div class="ml-lg-5 float-right">
              <%= paginate @users %>
            </div>
          </div>
        </div>
      <% else %>
        <div class="ml-lg-5 mb-4 p-4 text-dark border-corner text-center">
          <img src= "<%= image_url('no-content-found.svg') %>" width= "60%" height= "60%" loading="lazy">
          <div class="text-center" style="display: inline-block;">
            <span>No Users found </span>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-3">
      <div class="mb-4 text-dark">
        <h5 class="mb-3"><b>Ads will be here!</b></h5>
      </div>
    </div>
  </div>
</div>

app/views/home/trending.html.erb
<% content_for :title, 'Trending Publishers | Trending Tags | Trending Articles' %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-10 px-lg-0">
      <div class="row">
        <div class="col-md-9 mb-5">
          <div class="mb-5">
            <h5 class="mb-3 c-wrap"><b>Trending Publishers</b></h5>
            <div class="row flex-row flex-nowrap trending-users">
              <% @trending_users.each do |user|%>
                <div class="px-3">
                  <%= link_to user_path(id: user.username) do %>
                    <div class="trending-card">
                      <div class="user-image">
                        <% if user.avatar.present? %>
                          <img src="<%= user.avatar %>" class="rounded-circle" alt="user">
                        <% else %>
                          <img class="card-img-top p-3" src="<%= image_url('default_user.png') %>" alt="user">
                        <% end %>
                      </div>
                      <div class="user-detail-body text-center">
                        <h5 class="user-detail-name mb-0 font-weight-bold"><%= user.name %></h5>
                        <p class="user-detail-username mb-0"> &#64;<%= user.username %></p>
                        <p class="user-detail-count mb-0"><b><%= user.blogs_count %></b> Articles published</p>
                        <hr class="my-2">
                        <p class="user-detail-stats mb-0 f12"> 23k Views &amp; 30 Hearts</p>
                      </div>
                    </div>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
          <h5 class="mb-3 c-wrap"><b>Trending Articles</b></h5>
          <%= render 'blogs/blogs' %>
        </div>
        <div class="col-md-3">
          <div class="mb-4 text-dark">
            <h5 class="mb-3"><b>Trending tags</b></h5>
            <% @trending_tags.each do |tag| %>
              <%= link_to tag_path(tag.slug) do %>
                <button type="button" class="btn btn-theme mr-2 mb-2 tags-hover">
                  <b><%= tag.name %> <span class="badge badge-light"><%= tag.count %></span></b>
                </button>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>