config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  root to: 'blogs#index'
  resources :blogs, except: [:show] do
    member do
      post 'like'
      post 'bookmark' => 'users#bookmark'
    end
  end
  resources :comments
  resources :tags
  get 'tags-name-list' => 'tags#name_list'
  get '/trending' => 'home#trending', as: 'trending'
  get '/search' => 'home#search', as: 'search'
  resources :categories
  post '/follow_update' => 'followers#follow_update'
  devise_for :users, :controllers => {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "sessions",
    registrations: "registrations"
  }
  get '/bookmarked-articles' => 'users#bookmarked', as: 'bookmarked_articles'
  resources :users, only: [:show, :edit, :update] do
    member do
      put 'update_username'
      get 'comments'
      get 'following/suggestions' => 'users#following_suggestions', as: 'follow_suggestions'
      get 'following/categories' => 'users#following_categories', as: 'follow_categories'
      get 'following/people' => 'users#following_people', as: 'follow_people'
      get 'following/tags' => 'users#following_tags', as: 'follow_tags'
    end
  end
  get '/:category_id/:id' => 'blogs#show', as: 'blog_show'
  post '/image_upload' => 'attachments#image_upload'
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm py-1 <%= 'mb-5' unless (controller_name == 'blogs' && action_name == 'index') %>">
  <div class="container">
    <div class="navigation">
      <%= link_to root_path, class: "navbar-brand" do %>
        <img src= "<%= image_url("bootstrap-solid.svg") %>" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
      <% end %>
      <div class="navigation-menu">
        <div class="navigation-item order-1"  data-container="body" data-toggle="popover" data-placement="top" data-content="Trending" data-trigger="hover">
          <%= link_to trending_path, class: 'ico-nav-link btn btn-light' do %>
            <i class="fas fa-fire c-dark"></i>
          <% end %>
        </div>
        <div class="navigation-item order-2"  data-container="body" data-toggle="popover" data-placement="top" data-content="Popular" data-trigger="hover">
          <%= link_to trending_path, class: 'ico-nav-link btn btn-light' do %>
            <i class="fas fa-chart-line c-dark"></i>
          <% end %>
        </div>
        <%= form_with url: search_path, local: true, method: :get, html: { class: 'form-inline search-nav-form mx-1 order-last order-lg-3' } do |form| %>
          <%= form.text_field :q, placeholder: 'Search', class: 'form-control c-input rounded-0', style: 'width: 250px;', 'aria-label': "Search", data: { behavior: 'autocomplete' } %>
          <%= form.button 'Search', class: 'btn btn-theme btn-sm nav-search rounded-0' %>
        <% end %>
        <% if current_user %>
          <div class="navigation-item order-4">
            <a class="ico-nav-link btn btn-light waves-effect waves-light"><i class="fas fa-bell c-dark"></i></a>
          </div>
          <div class="navigation-item order-5">
            <%= link_to bookmarked_articles_path, class: 'ico-nav-link btn btn-light waves-effect waves-light' do %>
              <i class="fas fa-bookmark c-dark"></i>
            <% end %>
          </div>
          <div class="navigation-item dropdown order-6">
            <a class="ico-nav-link btn btn-light dropdown-toggle" href="#" id="navbarDropdown_profile" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-user c-dark"></i>
            </a>
            <div >
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown_profile">
              <%= link_to 'Create Blog', new_blog_path, class: "dropdown-item" %>
              <a class="dropdown-item" href="<%= user_path(current_user.username) %>">My Dashboard</a>
              <a class="dropdown-item" href="<%= follow_suggestions_user_path(current_user.username) %>">Manage Following</a>
              <a class="dropdown-item" href="#">My Performance</a>
              <a class="dropdown-item" href="<%= edit_user_path(current_user.username) %>">Edit Profile</a>
              <a class="dropdown-item" href="#">Settings</a>
              <a class="dropdown-item" href="#">Recent Activity</a>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </div>
        <% else %>
          <div class="navigation-item order-last ml-2">
            <div class="cd-main-nav__list js-signin-modal-trigger">
              <%= link_to new_user_session_path do %>
                Login / SignUp
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_login.html.erb
<%= stylesheet_link_tag 'login_signup/style' %>

<p id="notice"><%= notice %></p>
<div class="login-form">
  <div class="form-box">
    <div class="button-box">
      <div id="login-form-btn"></div>
      <button type="button" class="toggle-btn text-white" onclick="login()">Log In</button>
      <button type="button" class="toggle-btn" onclick="register()">Register</button>
    </div>
    <div class="social-icons">
      <%- resource_class.omniauth_providers.each do |provider| %>
        <% if provider == :google_oauth2 %>
          <%= link_to omniauth_authorize_path(resource_name, provider) do %>
            <img src="https://res-4.cloudinary.com/linkisin/image/asset/f_auto,fl_lossy,q_auto/google-icon-252d781740e912efab287591e0942093.png" alt="Google icon">
          <% end %>
        <% elsif provider == :facebook %>
          <%= link_to omniauth_authorize_path(resource_name, provider) do %>
            <img src="https://res-1.cloudinary.com/linkisin/image/asset/f_auto,fl_lossy,q_auto/facebook-icon-244d6370cec26acde422cfaaf439a7f1.png" alt="Facebook icon">
          <% end %>
        <% end %>
      <% end %>
    </div>
    <%= form_for(resource, as: resource_name, url: session_path(resource_name), html: { class: "input-group", id: "login" }, remote: true) do |f| %>
      <p class="error error-msg"></p>
      <%= f.email_field :email, autofocus: true, autocomplete: "email", id: 'login-email',class: "input-field", placeholder: 'Enter Email', required: true %>
      <%= f.password_field :password, autocomplete: "current-password", id: 'login-password',class: "input-field", placeholder: "Enter Password", required: true %>
      <% if devise_mapping.rememberable? %>
        <div class="field">
          <%= f.check_box :remember_me, class: "check-box" %>
          <%= f.label :remember_me, 'Remember Password' %>
        </div>
        <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
          <%= link_to "Forgot your password?", new_password_path(resource_name), class: 'mb-4' %>
        <% end %>
      <% end %>
      <%= f.submit "Log in", class: "submit-btn" %>
    <% end %>
  </div>
</div>

app/views/layouts/_login_modal.html.erb
<div class="modal hide" id="login_modal" aria-hidden="true" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" style="padding: 10px;" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= render 'layouts/login_signup' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_login_signup.html.erb
<%= stylesheet_link_tag 'login_signup/style' %>

<p id="notice"><%= notice %></p>
<div class="login-form">
  <div class="form-box">
    <div class="button-box">
      <div id="btn"></div>
      <button type="button" class="toggle-btn" onclick="login()">Log In</button>
      <button type="button" class="toggle-btn" onclick="register()">Register</button>
    </div>
    <div class="social-icons">
      <%- resource_class.omniauth_providers.each do |provider| %>
        <% if provider == :google_oauth2 %>
          <%= link_to omniauth_authorize_path(resource_name, provider) do %>
            <img src="https://res-4.cloudinary.com/linkisin/image/asset/f_auto,fl_lossy,q_auto/google-icon-252d781740e912efab287591e0942093.png" alt="Google icon">
          <% end %>
        <% elsif provider == :facebook %>
          <%= link_to omniauth_authorize_path(resource_name, provider) do %>
            <img src="https://res-1.cloudinary.com/linkisin/image/asset/f_auto,fl_lossy,q_auto/facebook-icon-244d6370cec26acde422cfaaf439a7f1.png" alt="Facebook icon">
          <% end %>
        <% end %>
      <% end %>
    </div>
    <%= form_for(resource, as: resource_name, url: session_path(resource_name), html: { class: "input-group", id: "login" }) do |f| %>
      <%= f.email_field :email, autofocus: true, autocomplete: "email", id: 'login-email',class: "input-field", placeholder: 'Enter Email', required: true %>
      <%= f.password_field :password, autocomplete: "current-password", id: 'login-password',class: "input-field", placeholder: "Enter Password", required: true %>
      <% if devise_mapping.rememberable? %>
        <div class="field">
          <%= f.check_box :remember_me, class: "check-box" %>
          <%= f.label :remember_me, 'Remember Password' %>
        </div>
        <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
          <%= link_to "Forgot your password?", new_password_path(resource_name), class: 'mb-4' %>
        <% end %>
      <% end %>
      <%= f.submit "Log in", class: "submit-btn" %>
    <% end %>
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { class: 'input-group', id: 'register' }) do |f| %>
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "input-field", placeholder: 'Enter Email', required: true %>
      <%= f.password_field :password, autocomplete: "new-password", placeholder: 'Enter Password', class: 'input-field', required: "true" %>
      <%= f.password_field :password_confirmation, autocomplete: "new-password", placeholder: 'Re-Enter Password', class: 'input-field', required: "true" %>
      <input type="checkbox" name="remember" class="check-box" required="true"><span>I agree to the Terms and Conditions</span>
      <%= f.submit "Sign up", class: "submit-btn" %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  var x = document.getElementById("login");
  var y = document.getElementById("register");
  var z = document.getElementById("btn");

  function register(){
    x.style.left = "-400px";
    y.style.left = "50px";
    z.style.left = "110px";
  }

  function login(){
    x.style.left = "50px";
    y.style.left = "450px";
    z.style.left = "0px";
  }
</script>

app/views/layouts/_meta_tags.html.erb
<meta name="title" content="<%= meta_title %>"/>
<meta name="description" content="<%= meta_description %>"/>

<meta property="og:title" content="<%= meta_title %>"/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="<%= request.original_url %>"/>
<meta property="og:image" content="<%= meta_image %>"/>
<meta property="og:description" content="<%= meta_description %>"/>
<meta property="og:site_name" content="<%= meta_title %>"/>

<meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:site" content="<%= DEFAULT_META['twitter_account'] %>"/>
<meta name="twitter:title" content="<%= meta_title %>"/>
<meta name="twitter:description" content="<%= meta_description %>"/>
<meta name="twitter:creator" content="<%= DEFAULT_META['twitter_account'] %>"/>
<meta name="twitter:image:src" content="<%= meta_image %>"/>

app/views/layouts/_signup.html.erb
<%= stylesheet_link_tag 'login_signup/style' %>

<p id="notice"><%= notice %></p>
<div class="login-form">
  <div class="form-box">
    <div class="button-box">
      <div id="login-form-btn" style="left: 125px;"></div>
      <button type="button" class="toggle-btn" onclick="login()">Log In</button>
      <button type="button" class="toggle-btn text-white" onclick="register()">Register</button>
    </div>
    <div class="social-icons">
      <%- resource_class.omniauth_providers.each do |provider| %>
        <% if provider == :google_oauth2 %>
          <%= link_to omniauth_authorize_path(resource_name, provider) do %>
            <img src="https://res-4.cloudinary.com/linkisin/image/asset/f_auto,fl_lossy,q_auto/google-icon-252d781740e912efab287591e0942093.png" alt="Google icon">
          <% end %>
        <% elsif provider == :facebook %>
          <%= link_to omniauth_authorize_path(resource_name, provider) do %>
            <img src="https://res-1.cloudinary.com/linkisin/image/asset/f_auto,fl_lossy,q_auto/facebook-icon-244d6370cec26acde422cfaaf439a7f1.png" alt="Facebook icon">
          <% end %>
        <% end %>
      <% end %>
    </div>
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { class: 'input-group', id: 'register' }, remote: true) do |f| %>
      <p class="error error-msg"></p>
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "input-field", placeholder: 'Enter Email', required: true %>
      <%= f.password_field :password, autocomplete: "new-password", placeholder: 'Enter Password', class: 'input-field', required: "true" %>
      <%= f.password_field :password_confirmation, autocomplete: "new-password", placeholder: 'Re-Enter Password', class: 'input-field', required: "true" %>
      <input type="checkbox" name="remember" class="check-box" required="true"><span>I agree to the Terms and Conditions</span>
      <%= f.submit "Sign up", class: "submit-btn" %>
    <% end %>
  </div>
</div>

app/views/layouts/_signup_modal.html.erb
<div class="modal hide" id="signup_modal" aria-hidden="true" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" style="padding: 10px;" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= render 'layouts/signup' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% unless controller_name == 'blogs' && action_name == 'index' %>
      <title><%= yield(:title) %> | Knowledge Gang</title>
    <% else %>
      <title>Knowledge Gang | Share your knowledge for Cricket, Bollywood, Startups, Mythology, Gaming, Politics, Fitness</title>
    <% end %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render 'layouts/meta_tags' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/caf30f105c.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% if notice %>
      <p class="notice alert alert-success" role="alert"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger" role="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
    <%= render 'layouts/login_modal' %>
    <%= render 'layouts/signup_modal' %>
  </body>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'tags' %>
  <%= javascript_include_tag 'typeahead' %>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
  
</html>